### ISSUE TITLE
list_plugins() displaying each plugin twice, but I'm probably mistaken about something

### ISSUE THREAD

**Issue by shmup** [mitsuhiko/pluginbase#15]
```
$ tree -I 'venv|.git|__pycache__'
.
├── app.py
└── sources
    ├── one.py
    └── two.py
```

```
from pluginbase import PluginBase

plugin_base = PluginBase(package='app.sources')
plugin_source = plugin_base.make_plugin_source(searchpath=['./sources'])

for plugin_name in plugin_source.list_plugins():
    print(plugin_name)
```

And when running app.py, I see:

```
:!/usr/bin/env python app.py
one
two
one
two
```

If you could kindly point out the error I'm most definitely making, that'd be cool.

**Comment by shmup** [comment]
Annnnnd, okay. So I'm probably mistaken about what this is really doing/requiring: _Create a “plugin base” object. It defines a pseudo package under which all your plugins will reside. For instance it could be yourapplication.plugins_

Adjusting my line above to `plugin_base = PluginBase(package='sources.foo')` does resolve the issue. 

I probably took that convention from [your example](https://github.com/mitsuhiko/pluginbase/blob/master/example/example.py#L13).

Could you help shed some clarity?

**Comment by zeroSteiner** [comment]
The package parameter is the name of a module to use for the plugins. What I think happened was that because your package name was the same as if it were a traditional python package, the plugins were loaded twice. Under your sources do you have an `__init__.py` file? That's not necessary for the folder to function as a source for plugins.
